# Generated by Django 4.1.2 on 2022-10-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clean', models.CharField(choices=[('T', 'Teeth'), ('H', 'Hair'), ('N', 'Nails')], default='T', max_length=1)),
                ('capybara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.capybara')),
            ],
        ),
    ]
